### ISSUE TITLE
The algorithm terminates with PB = Inf and finite DB

### ISSUE THREAD

**Issue by trathi05** [atoptima/Coluna.jl#604] opened 2021-09-16 20:51 UTC
**Describe the bug**
In the problem I am solving, I use `ColumnGeneration()` as the top solver. However, it seems to terminate in around a minute even when the `PB` and `DB` are yet to converge.

```
coluna = optimizer_with_attributes(
            Coluna.Optimizer,
            "params" => Coluna.Params(
                solver = Coluna.Algorithm.ColumnGeneration() ),
                "default_optimizer" => Gurobi.Optimizer
            );
```

**To Reproduce**
I don't have an MWE yet. I will try to make one if this is the first time such an issue is seen.

**Expected behavior**
There are a couple of points:
1. Of course, I would expect the algorithm to converge only if the PB-LB < tolerance. However, Is this because Coluna has solved the root node relaxation but it has not been able to find an integer feasible solution to the problem; hence `PB = Inf`?
2.  Since, I am calling `ColumnGeneration` I do not understand why the column generation is run thrice at the root node (`[ Info: Column generation algorithm has converged.` prints thrice in the log)  
```
  <it=  1> <et= 9.02> <mst= 1.78> <sp= 3.34> <cols= 0> <al= 0.00> <DB=32128588955.2987> <mlp=80000.0000> <PB=Inf>
[ Info: Column generation algorithm has converged.
# <it=  1> <et=10.54> <mst= 0.05> <sp= 0.73> <cols= 8> <al= 0.00> <DB=    0.0000> <mlp=80000.0000> <PB=Inf>
# <it=  2> <et=11.32> <mst= 0.10> <sp= 0.69> <cols=12> <al= 0.00> <DB=    0.0000> <mlp=80000.0000> <PB=Inf>
# <it=  3> <et=12.05> <mst= 0.06> <sp= 0.67> <cols=10> <al= 0.00> <DB=    0.0000> <mlp=80000.0000> <PB=Inf>
# <it=  4> <et=12.78> <mst= 0.07> <sp= 0.66> <cols=11> <al= 0.00> <DB=    0.0000> <mlp=80000.0000> <PB=Inf>
# <it=  5> <et=13.55> <mst= 0.09> <sp= 0.68> <cols=11> <al= 0.00> <DB=    0.0000> <mlp=80000.0000> <PB=Inf>
# <it=  6> <et=14.29> <mst= 0.10> <sp= 0.66> <cols=12> <al= 0.00> <DB=    0.0000> <mlp=53200.0000> <PB=Inf>
# <it=  7> <et=15.13> <mst= 0.10> <sp= 0.73> <cols=11> <al= 0.00> <DB=    0.0000> <mlp=36607.1180> <PB=Inf>
# <it=  8> <et=15.83> <mst= 0.10> <sp= 0.60> <cols=10> <al= 0.00> <DB=    0.0000> <mlp=22858.3897> <PB=Inf>
# <it=  9> <et=16.57> <mst= 0.10> <sp= 0.63> <cols= 8> <al= 0.00> <DB=    0.0000> <mlp=16362.2934> <PB=Inf>
# <it= 10> <et=17.35> <mst= 0.10> <sp= 0.68> <cols=12> <al= 0.00> <DB=    0.0000> <mlp=10662.5708> <PB=Inf>
# <it= 11> <et=18.16> <mst= 0.09> <sp= 0.73> <cols=15> <al= 0.00> <DB=    0.0000> <mlp= 7841.0939> <PB=Inf>
# <it= 12> <et=18.86> <mst= 0.09> <sp= 0.60> <cols= 8> <al= 0.00> <DB=    0.0000> <mlp= 6379.1192> <PB=Inf>
# <it= 13> <et=19.67> <mst= 0.09> <sp= 0.71> <cols= 9> <al= 0.00> <DB=    0.0000> <mlp= 4524.0257> <PB=Inf>
# <it= 14> <et=20.51> <mst= 0.10> <sp= 0.74> <cols=13> <al= 0.00> <DB=    0.0000> <mlp= 3261.4816> <PB=Inf>
# <it= 15> <et=21.45> <mst= 0.12> <sp= 0.82> <cols=20> <al= 0.00> <DB=    0.0000> <mlp= 2189.9489> <PB=Inf>
# <it= 16> <et=22.35> <mst= 0.13> <sp= 0.78> <cols=18> <al= 0.00> <DB=    0.0000> <mlp= 1351.3125> <PB=Inf>
# <it= 17> <et=23.34> <mst= 0.16> <sp= 0.81> <cols=18> <al= 0.00> <DB=    0.0000> <mlp=  612.5653> <PB=Inf>
# <it= 18> <et=24.32> <mst= 0.23> <sp= 0.77> <cols=17> <al= 0.00> <DB=    0.0000> <mlp=  131.7807> <PB=Inf>
# <it= 19> <et=24.94> <mst= 0.21> <sp= 0.40> <cols= 1> <al= 0.00> <DB=    0.0000> <mlp=    0.0000> <PB=Inf>
[ Info: Column generation algorithm has converged.
##<it=  1> <et=26.50> <mst= 0.12> <sp= 1.26> <cols=41> <al= 0.00> <DB=32039353780.5520> <mlp=32133890723.9105> <PB=Inf>
##<it=  2> <et=27.68> <mst= 0.20> <sp= 0.97> <cols=22> <al= 0.00> <DB=32109920481.3291> <mlp=32133662948.9223> <PB=Inf>
##<it=  3> <et=29.08> <mst= 0.25> <sp= 1.14> <cols=25> <al= 0.00> <DB=32109920481.3291> <mlp=32133119401.0808> <PB=Inf>
##<it=  4> <et=30.25> <mst= 0.26> <sp= 0.90> <cols=20> <al= 0.00> <DB=32109920481.3291> <mlp=32132628743.8796> <PB=Inf>
##<it=  5> <et=31.70> <mst= 0.25> <sp= 1.20> <cols=32> <al= 0.00> <DB=32109920481.3291> <mlp=32132160757.9158> <PB=Inf>
##<it=  6> <et=33.00> <mst= 0.30> <sp= 1.00> <cols=29> <al= 0.00> <DB=32118182977.1438> <mlp=32131616661.6540> <PB=Inf>
##<it=  7> <et=34.51> <mst= 0.26> <sp= 1.09> <cols=32> <al= 0.00> <DB=32118182977.1438> <mlp=32131090195.8213> <PB=Inf>
##<it=  8> <et=35.74> <mst= 0.23> <sp= 1.00> <cols=19> <al= 0.00> <DB=32118182977.1438> <mlp=32130752920.2475> <PB=Inf>
##<it=  9> <et=36.93> <mst= 0.27> <sp= 0.90> <cols=21> <al= 0.00> <DB=32119332404.7517> <mlp=32130477081.9616> <PB=Inf>
##<it= 10> <et=38.28> <mst= 0.23> <sp= 1.12> <cols=29> <al= 0.00> <DB=32120370412.8720> <mlp=32130330664.2190> <PB=Inf>
##<it= 11> <et=39.69> <mst= 0.24> <sp= 1.15> <cols=23> <al= 0.00> <DB=32122215729.7842> <mlp=32130140184.2889> <PB=Inf>
##<it= 12> <et=40.75> <mst= 0.27> <sp= 0.78> <cols=18> <al= 0.00> <DB=32122215729.7842> <mlp=32129958174.8437> <PB=Inf>
##<it= 13> <et=41.95> <mst= 0.23> <sp= 0.97> <cols=18> <al= 0.00> <DB=32123245984.3803> <mlp=32129848678.7251> <PB=Inf>
##<it= 14> <et=43.07> <mst= 0.22> <sp= 0.88> <cols=20> <al= 0.00> <DB=32123245984.3803> <mlp=32129690838.6243> <PB=Inf>
##<it= 15> <et=44.40> <mst= 0.26> <sp= 1.06> <cols=21> <al= 0.00> <DB=32123245984.3803> <mlp=32129572763.7809> <PB=Inf>
##<it= 16> <et=45.54> <mst= 0.27> <sp= 0.85> <cols=16> <al= 0.00> <DB=32125060695.9306> <mlp=32129468209.2368> <PB=Inf>
##<it= 17> <et=46.84> <mst= 0.23> <sp= 1.08> <cols=21> <al= 0.00> <DB=32125136727.3888> <mlp=32129379218.5844> <PB=Inf>
##<it= 18> <et=47.77> <mst= 0.20> <sp= 0.73> <cols= 9> <al= 0.00> <DB=32125922484.0240> <mlp=32129340177.2166> <PB=Inf>
##<it= 19> <et=49.08> <mst= 0.22> <sp= 1.07> <cols=22> <al= 0.00> <DB=32125922484.0240> <mlp=32129289501.5093> <PB=Inf>
##<it= 20> <et=50.22> <mst= 0.22> <sp= 0.91> <cols=17> <al= 0.00> <DB=32125922484.0240> <mlp=32129229125.7763> <PB=Inf>
##<it= 21> <et=51.44> <mst= 0.24> <sp= 0.83> <cols=17> <al= 0.00> <DB=32126151411.3372> <mlp=32129148091.1589> <PB=Inf>
##<it= 22> <et=52.69> <mst= 0.21> <sp= 1.02> <cols=17> <al= 0.00> <DB=32126185394.3943> <mlp=32129116802.1748> <PB=Inf>
##<it= 23> <et=53.62> <mst= 0.21> <sp= 0.71> <cols=11> <al= 0.00> <DB=32126185394.3943> <mlp=32129055097.9724> <PB=Inf>
##<it= 24> <et=54.91> <mst= 0.24> <sp= 1.03> <cols=16> <al= 0.00> <DB=32126185394.3943> <mlp=32129025616.7934> <PB=Inf>
##<it= 25> <et=56.17> <mst= 0.27> <sp= 0.98> <cols=22> <al= 0.00> <DB=32126538791.0719> <mlp=32128972344.7676> <PB=Inf>
##<it= 26> <et=57.39> <mst= 0.27> <sp= 0.95> <cols=12> <al= 0.00> <DB=32126538791.0719> <mlp=32128930489.8708> <PB=Inf>
##<it= 27> <et=58.42> <mst= 0.25> <sp= 0.76> <cols= 9> <al= 0.00> <DB=32126750047.2682> <mlp=32128893025.5296> <PB=Inf>
##<it= 28> <et=59.71> <mst= 0.23> <sp= 1.05> <cols=19> <al= 0.00> <DB=32126750047.2682> <mlp=32128869708.6798> <PB=Inf>
##<it= 29> <et=61.07> <mst= 0.24> <sp= 1.11> <cols=16> <al= 0.00> <DB=32126750047.2682> <mlp=32128831350.9868> <PB=Inf>
##<it= 30> <et=62.15> <mst= 0.24> <sp= 0.82> <cols=14> <al= 0.00> <DB=32126756971.9639> <mlp=32128784775.9092> <PB=Inf>
##<it= 31> <et=63.35> <mst= 0.22> <sp= 0.98> <cols=13> <al= 0.00> <DB=32126756971.9639> <mlp=32128757993.6764> <PB=Inf>
##<it= 32> <et=64.46> <mst= 0.21> <sp= 0.89> <cols=18> <al= 0.00> <DB=32126756971.9639> <mlp=32128710847.2517> <PB=Inf>
##<it= 33> <et=65.51> <mst= 0.18> <sp= 0.86> <cols=10> <al= 0.00> <DB=32126756971.9639> <mlp=32128677078.2197> <PB=Inf>
##<it= 34> <et=66.46> <mst= 0.17> <sp= 0.78> <cols=12> <al= 0.00> <DB=32126897499.0268> <mlp=32128648849.4602> <PB=Inf>
##<it= 35> <et=67.52> <mst= 0.15> <sp= 0.90> <cols=11> <al= 0.00> <DB=32127411323.0436> <mlp=32128635079.4138> <PB=Inf>
##<it= 36> <et=68.45> <mst= 0.17> <sp= 0.75> <cols= 9> <al= 0.00> <DB=32127489712.5091> <mlp=32128610648.1379> <PB=Inf>
##<it= 37> <et=69.44> <mst= 0.14> <sp= 0.84> <cols= 7> <al= 0.00> <DB=32127538905.2708> <mlp=32128600168.1023> <PB=Inf>
##<it= 38> <et=70.32> <mst= 0.12> <sp= 0.74> <cols=10> <al= 0.00> <DB=32127690743.0182> <mlp=32128592128.2208> <PB=Inf>
##<it= 39> <et=71.35> <mst= 0.15> <sp= 0.88> <cols= 9> <al= 0.00> <DB=32127690743.0182> <mlp=32128579516.6064> <PB=Inf>
##<it= 40> <et=72.23> <mst= 0.20> <sp= 0.67> <cols= 7> <al= 0.00> <DB=32127690743.0182> <mlp=32128561944.8845> <PB=Inf>
##<it= 41> <et=73.13> <mst= 0.17> <sp= 0.72> <cols= 8> <al= 0.00> <DB=32127690743.0182> <mlp=32128553306.7497> <PB=Inf>
##<it= 42> <et=74.08> <mst= 0.11> <sp= 0.83> <cols= 9> <al= 0.00> <DB=32127690743.0182> <mlp=32128543393.5450> <PB=Inf>
##<it= 43> <et=74.91> <mst= 0.15> <sp= 0.66> <cols= 7> <al= 0.00> <DB=32127690743.0182> <mlp=32128523033.1075> <PB=Inf>
##<it= 44> <et=75.72> <mst= 0.15> <sp= 0.65> <cols= 5> <al= 0.00> <DB=32127740378.3689> <mlp=32128513248.6938> <PB=Inf>
##<it= 45> <et=76.65> <mst= 0.13> <sp= 0.79> <cols= 6> <al= 0.00> <DB=32127842900.9585> <mlp=32128497544.3974> <PB=Inf>
##<it= 46> <et=77.55> <mst= 0.16> <sp= 0.74> <cols=10> <al= 0.00> <DB=32127842900.9585> <mlp=32128490660.1265> <PB=Inf>
##<it= 47> <et=78.60> <mst= 0.16> <sp= 0.87> <cols= 9> <al= 0.00> <DB=32127842900.9585> <mlp=32128478050.9717> <PB=Inf>
##<it= 48> <et=79.44> <mst= 0.19> <sp= 0.65> <cols= 6> <al= 0.00> <DB=32127910566.5831> <mlp=32128469178.7854> <PB=Inf>
##<it= 49> <et=80.25> <mst= 0.10> <sp= 0.70> <cols= 6> <al= 0.00> <DB=32128117517.5083> <mlp=32128468259.5503> <PB=Inf>
##<it= 50> <et=81.15> <mst= 0.10> <sp= 0.79> <cols= 7> <al= 0.00> <DB=32128117517.5083> <mlp=32128460788.0645> <PB=Inf>
##<it= 51> <et=82.02> <mst= 0.15> <sp= 0.70> <cols= 9> <al= 0.00> <DB=32128117517.5083> <mlp=32128454059.2411> <PB=Inf>
##<it= 52> <et=82.83> <mst= 0.19> <sp= 0.62> <cols= 3> <al= 0.00> <DB=32128117517.5083> <mlp=32128445541.6813> <PB=Inf>
##<it= 53> <et=83.69> <mst= 0.12> <sp= 0.74> <cols= 3> <al= 0.00> <DB=32128117517.5083> <mlp=32128441714.8490> <PB=Inf>
##<it= 54> <et=84.41> <mst= 0.13> <sp= 0.57> <cols= 2> <al= 0.00> <DB=32128148768.8502> <mlp=32128439045.6763> <PB=Inf>
##<it= 55> <et=85.24> <mst= 0.11> <sp= 0.71> <cols= 8> <al= 0.00> <DB=32128148768.8502> <mlp=32128434212.9039> <PB=Inf>
##<it= 56> <et=86.03> <mst= 0.16> <sp= 0.63> <cols= 4> <al= 0.00> <DB=32128148768.8502> <mlp=32128414522.3524> <PB=Inf>
##<it= 57> <et=86.86> <mst= 0.11> <sp= 0.71> <cols= 3> <al= 0.00> <DB=32128148768.8502> <mlp=32128407291.1124> <PB=Inf>
##<it= 58> <et=87.55> <mst= 0.12> <sp= 0.56> <cols= 2> <al= 0.00> <DB=32128265772.0188> <mlp=32128403751.5278> <PB=Inf>
##<it= 59> <et=88.22> <mst= 0.09> <sp= 0.58> <cols= 1> <al= 0.00> <DB=32128411001.2769> <mlp=32128403751.1829> <PB=Inf>
[ Info: Column generation algorithm has converged.
 ────────────────────────────────────────────────────────────────────────────────────
                                             Time                   Allocations
                                     ──────────────────────   ───────────────────────
          Tot / % measured:               5716s / 1.55%           22.3GiB / 57.0%

 Section                     ncalls     time   %tot     avg     alloc   %tot      avg
 ────────────────────────────────────────────────────────────────────────────────────
 Coluna                           1    88.6s   100%   88.6s   12.7GiB  100%   12.7GiB
   SolveLpForm                   79    14.8s  16.7%   187ms    206MiB  1.58%  2.60MiB
   Update reduced costs          79    1.56s  1.76%  19.7ms   1.49GiB  11.7%  19.3MiB
   Inserting columns             79    1.10s  1.24%  14.0ms    155MiB  1.19%  1.96MiB
   Getting primal solution       79    994ms  1.12%  12.6ms    439MiB  3.37%  5.56MiB
   Cleanup columns               79    203ms  0.23%  2.57ms   13.6MiB  0.10%   176KiB
   Update Lagrangian bound       79   78.1ms  0.09%   989μs   3.07MiB  0.02%  39.8KiB
   Smoothing update              79   18.8ms  0.02%   238μs   4.26MiB  0.03%  55.2KiB
 ────────────────────────────────────────────────────────────────────────────────────
[ Info: Terminated
[ Info: Primal bound: Inf
[ Info: Dual bound: 3.212841100127686e10
(MathOptInterface.OPTIMAL, Inf, 3.212841100127686e10, 88.664)
```

**Environment (please complete the following information):**
 - Julia 1.6.1
 - Windows
 - BlockDecomposition v1.4.0
 - Coluna v0.3.10
 - JuMP v0.21.8
 - Gurobi v0.9.13

Please if this is a bug or I am reading the log incorrectly. Also, is there a way I can feed an initial `PB` to Coluna?

**Comment by trathi05** [comment] 2021-09-16 21:23
Also, why does initiate the optimizer (below) throws the error `UndefVarError: ColCutGenConquer not defined`.

```
coluna = optimizer_with_attributes(
            Coluna.Optimizer,
            "params" => Coluna.Params(
                solver = Coluna.Algorithm.TreeSearchAlgorithm(conqueralg= ColCutGenConquer(),
                dividealg = SimpleBranching(),
               maxnumnodes = 1) ),
                "default_optimizer" => Gurobi.Optimizer
            );
```

The same error is thrown for the `SimpleBranching()` function. What am I doing wrongly? The error for `ColCutGenConquer()` is resolved if I instead write `conqueralg= Coluna.Algorithm.ColCutGenConquer()`.

**Comment by guimarqu** [comment] 2021-09-16 21:24
Hi,

This is not a bug.

In the column generation algorithm :
- DB stands for the current dual bound
- mlp stands for the objective value of the LP master 
- DB stands for the best feasible solution found to the IP master (best integer solution)

Column generation converges when DB and mlp have approximately the same values (it depends on the tolerance). It's the case here. 

PB is inf because column generation did no find any integer solution to your problem. 
You should use a heuristic or you can provide an initial primal bound. Here is the definition of the method :

https://github.com/atoptima/BlockDecomposition.jl/blob/e43aa9dab0328c5b02b1a4bc589a0af0d72a69a6/src/objective.jl#L10

I forgot to put this method in the documentation...

**Comment by guimarqu** [comment] 2021-09-16 21:32
> Also, why does initiate the optimizer (below) throws the error `UndefVarError: ColCutGenConquer not defined`.
> 
> 
> 
> ```
> 
> coluna = optimizer_with_attributes(
> 
>             Coluna.Optimizer,
> 
>             "params" => Coluna.Params(
> 
>                 solver = Coluna.Algorithm.TreeSearchAlgorithm(conqueralg= ColCutGenConquer(),
> 
>                 dividealg = SimpleBranching(),
> 
>                maxnumnodes = 1) ),
> 
>                 "default_optimizer" => Gurobi.Optimizer
> 
>             );
> 
> ```
> 
> 
> 
> The same error is thrown for the `SimpleBranching()` function. What am I doing wrongly? The error for `ColCutGenConquer()` is resolved if I instead write `conqueralg= Coluna.Algorithm.ColCutGenConquer()`.

It's because we don't export these methods. Maybe we should export them to make the configuration less verbose. 

I think `Coluna.Algorithm.SimpleBranching()` will work.

**Comment by trathi05** [comment] 2021-09-16 21:37
> PB is inf because column generation did no find any integer solution to your problem.

That's what I thought. Thanks for confirming this.

> I think `Coluna.Algorithm.SimpleBranching()` will work.

This works.

**Comment by trathi05** [comment] 2021-09-16 22:15
Hi,

I had a couple of more questions:
1. I get an error when I try to ass parameters like `smoothing_stabilization` to `ColumnGeneration`.
```
coluna = optimizer_with_attributes(
            Coluna.Optimizer,
            "params" => Coluna.Params(
                solver = Coluna.Algorithm.TreeSearchAlgorithm(conqueralg= Coluna.Algorithm.ColumnGeneration(
                    smoothing_stabilization = 1.0 
                ),
                dividealg = Coluna.Algorithm.SimpleBranching(),
               maxnumnodes = 100) ),
                "default_optimizer" => Gurobi.Optimizer
            );
```
`ERROR: MethodError: Cannot convert an object of type Coluna.Algorithm.ColumnGeneration to an object of type Coluna.Algorithm.AbstractConquerAlgorithm`

2. Is there a way to query the gap (i.e. `|mlp-DB|/|mlp|`) at every iteration of column generation if I am only interested in solving the relaxation of the original problem at the root node. In other words, I just want to apply the column generation to my problem at the root node and want the gap at every iteration. Is this possible?

**Comment by guimarqu** [comment] 2021-09-18 12:35
Hi,

1. You need to pass [`ColCutGenConquer`](https://atoptima.github.io/Coluna.jl/latest/man/algorithm/#Coluna.Algorithm.ColCutGenConquer) algorithm for `conqueralg` and then you can configure the column generation algorithm (`stages` field).

2. Sure by redefining the following method in your code : 

https://github.com/atoptima/Coluna.jl/blob/00b48ec371e67a82aa8c25669ab895e26786ff43/src/Algorithm/colgen.jl#L819-L822

**Comment by guimarqu** [comment] 2021-09-18 12:37
I close the issue because it turns out that the method to define an initial bound is the documentation : https://atoptima.github.io/Coluna.jl/latest/man/config/#From-BlockDecomposition

Feel free to open a new issue when you face some problems.

**Closed by guimarqu** 2021-09-18 12:37 UTC
